=== SynapseProject/Syntinel.Design/schemas/signal.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "required": [ "name", "description", "signal", "cues" ],
    "properties": {
        "name": { "type": "string" },
        "description": { "type": "string" },
        "allowMultiple": { "type": "boolean" },
        "signal": { 
            "type": "object",
            "properties": {
                "reporterId": { "type": "integer" },
                "type": { "type": "string" },
                "group": { "type": "string" },
                "id": { "type": "string" }
            }
        },
        "cues": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [ "id", "name", "description", "resolver" ],
                "properties": {
                    "id": { "type": "string" },
                    "name": { "type": "string" },
                    "description": { "type": "string" },
                    "resolver": {
                        "type": "object",
                        "required": [ "type" ],
                        "properties": {
                            "type": { "type": "string" },
                            "action": { "type": "string" },
                            "variables": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "required": ["name", "type"],
                                    "properties": {
                                        "name": { "type": "string" },
                                        "type": { "type": "string" },
                                        "defaultValue": { "type": "string" },
                                        "options": { "type": "array" }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "defaultCue": { "type": "string" },
        "defaultCueTimeout": { "type": "integer" }
    }
}

=== SynapseProject/Syntinel.Design/mockups/Signal-Mockup.json
{
   "name": "Utilization",
   "description": "EC2 Utilization Montior",
   "allowMultiple": false,
   "signal": {
       "reporterId": 1,
       "type": "HighCpu",
       "group": "WU2-P1-0317",
       "id": "i-06a81abcd8caa4843"
   },
   "cues": [
       {
           "id": "resize",
           "name": "EC2 Resize",
           "description": "WU2P103170042 (t2.large) is 43% utilizied for the past 7 days.  Would you like to resize it?",
           "resolver": {
               "type": "Lambda",
               "action": "MyTestResolver",
               "variables": [
                   {
                       "name": "size",
                       "type": "list",
                       "options": [
                           "t2.nano",
                           "t2.micro",
                           "t2.medium",
                           "Ignore"
                       ],
                       "defaultValue": "t2.nano"
                   },
                   {
                      "name": "instanceid",
                      "type": "hidden",
                      "defaultValue": "i-06a81abcd8caa4843"
                   }
               ]
           }
       }
   ],
   "defaultCue": "resize",
   "defaultCueTimeout": 4320
}
