=== SynapseProject/Syntinel.Design/schemas/status.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "required": [ "id" ],
    "properties": {
        "id": { "type": "string" },
        "actionId": { "type": "string" },
        "status": { "type": "string" },
        "closeSignal": { "type": "boolean" },
        "isValidReply": { "type": "boolean" },
        "data": { "type": "object" }
    }
}

=== SynapseProject/Syntinel.Design/mockups/Status-Mockup.json
{
    "id": "000000000",
    "actionId": "CUE-000000000",
    "status": "Completed",
    "closeSignal": true,
    "isValidReply": false,
    "data": { 
        "One": 111, 
        "Two": 222, 
        "Three": 333, 
        "Stuff": { 
            "SubOne": "One", 
            "SubTwo": "Two"
        } 
    }
  }
